// Predefined Spanish vocabulary list.
// en: English, es: Spanish, cat: category
// gender: "pair" marks a noun that inflects for gender. Such entries carry
//   m/f (the two Spanish forms) and enM/enF (the English label for each,
//   which differ when English is gendered too: hermano=brother, hermana=sister).
//   Nouns with a FIXED gender (mesa, libro) are deliberately not marked here --
//   there is no masculine "mesa" to ask for.
// invariable: true means the two forms are spelt identically (el/la cantante);
//   only the article differs, so the quiz asks for it with the article.
const WORDS = [
  // People & family
  { en: "man", es: "hombre", cat: "people" },
  { en: "woman", es: "mujer", cat: "people" },
  {
    en: "boy",
    es: "chico",
    cat: "people",
    gender: "pair",
    m: "chico",
    f: "chica",
    enM: "boy",
    enF: "girl",
  },
  {
    en: "child",
    es: "niño",
    cat: "people",
    gender: "pair",
    m: "niño",
    f: "niña",
    enM: "boy (child)",
    enF: "girl (child)",
  },
  { en: "father", es: "padre", cat: "people" },
  { en: "mother", es: "madre", cat: "people" },
  {
    en: "brother",
    es: "hermano",
    cat: "people",
    gender: "pair",
    m: "hermano",
    f: "hermana",
    enM: "brother",
    enF: "sister",
  },
  {
    en: "son",
    es: "hijo",
    cat: "people",
    gender: "pair",
    m: "hijo",
    f: "hija",
    enM: "son",
    enF: "daughter",
  },
  {
    en: "grandfather",
    es: "abuelo",
    cat: "people",
    gender: "pair",
    m: "abuelo",
    f: "abuela",
    enM: "grandfather",
    enF: "grandmother",
  },
  {
    en: "friend",
    es: "amigo",
    cat: "people",
    gender: "pair",
    m: "amigo",
    f: "amiga",
    enM: "friend",
    enF: "friend",
  },
  { en: "husband", es: "marido", cat: "people" },
  { en: "wife", es: "esposa", cat: "people" },
  {
    en: "neighbour",
    es: "vecino",
    cat: "people",
    gender: "pair",
    m: "vecino",
    f: "vecina",
    enM: "neighbour",
    enF: "neighbour",
  },
  {
    en: "teacher",
    es: "maestro",
    cat: "people",
    gender: "pair",
    m: "maestro",
    f: "maestra",
    enM: "teacher",
    enF: "teacher",
  },

  // Food & drink
  { en: "bread", es: "pan", cat: "food" },
  { en: "water", es: "agua", cat: "food" },
  { en: "milk", es: "leche", cat: "food" },
  { en: "wine", es: "vino", cat: "food" },
  { en: "beer", es: "cerveza", cat: "food" },
  { en: "coffee", es: "café", cat: "food" },
  { en: "cheese", es: "queso", cat: "food" },
  { en: "meat", es: "carne", cat: "food" },
  { en: "chicken", es: "pollo", cat: "food" },
  { en: "fish", es: "pescado", cat: "food" },
  { en: "egg", es: "huevo", cat: "food" },
  { en: "rice", es: "arroz", cat: "food" },
  { en: "apple", es: "manzana", cat: "food" },
  { en: "orange", es: "naranja", cat: "food" },
  { en: "strawberry", es: "fresa", cat: "food" },
  { en: "onion", es: "cebolla", cat: "food" },
  { en: "garlic", es: "ajo", cat: "food" },
  { en: "sugar", es: "azúcar", cat: "food" },
  { en: "salt", es: "sal", cat: "food" },
  { en: "breakfast", es: "desayuno", cat: "food" },
  { en: "dinner", es: "cena", cat: "food" },

  // Animals
  {
    en: "dog",
    es: "perro",
    cat: "animals",
    gender: "pair",
    m: "perro",
    f: "perra",
    enM: "dog",
    enF: "dog",
  },
  {
    en: "cat",
    es: "gato",
    cat: "animals",
    gender: "pair",
    m: "gato",
    f: "gata",
    enM: "cat",
    enF: "cat",
  },
  { en: "horse", es: "caballo", cat: "animals" },
  { en: "cow", es: "vaca", cat: "animals" },
  { en: "sheep", es: "oveja", cat: "animals" },
  { en: "bird", es: "pájaro", cat: "animals" },
  { en: "mouse", es: "ratón", cat: "animals" },
  { en: "bear", es: "oso", cat: "animals" },
  {
    en: "rabbit",
    es: "conejo",
    cat: "animals",
    gender: "pair",
    m: "conejo",
    f: "coneja",
    enM: "rabbit",
    enF: "rabbit",
  },
  { en: "spider", es: "araña", cat: "animals" },

  // House & objects
  { en: "house", es: "casa", cat: "house" },
  { en: "door", es: "puerta", cat: "house" },
  { en: "window", es: "ventana", cat: "house" },
  { en: "table", es: "mesa", cat: "house" },
  { en: "chair", es: "silla", cat: "house" },
  { en: "bed", es: "cama", cat: "house" },
  { en: "kitchen", es: "cocina", cat: "house" },
  { en: "bathroom", es: "baño", cat: "house" },
  { en: "key", es: "llave", cat: "house" },
  { en: "book", es: "libro", cat: "house" },
  { en: "pen", es: "bolígrafo", cat: "house" },
  { en: "clock", es: "reloj", cat: "house" },
  { en: "mirror", es: "espejo", cat: "house" },
  { en: "towel", es: "toalla", cat: "house" },
  { en: "money", es: "dinero", cat: "house" },

  // Places & travel
  { en: "city", es: "ciudad", cat: "places" },
  { en: "town", es: "pueblo", cat: "places" },
  { en: "street", es: "calle", cat: "places" },
  { en: "beach", es: "playa", cat: "places" },
  { en: "mountain", es: "montaña", cat: "places" },
  { en: "sea", es: "mar", cat: "places" },
  { en: "river", es: "río", cat: "places" },
  { en: "shop", es: "tienda", cat: "places" },
  { en: "market", es: "mercado", cat: "places" },
  { en: "school", es: "escuela", cat: "places" },
  { en: "church", es: "iglesia", cat: "places" },
  { en: "airport", es: "aeropuerto", cat: "places" },
  { en: "train", es: "tren", cat: "places" },
  { en: "car", es: "coche", cat: "places" },
  { en: "bridge", es: "puente", cat: "places" },

  // Time & nature
  { en: "day", es: "día", cat: "time" },
  { en: "night", es: "noche", cat: "time" },
  { en: "week", es: "semana", cat: "time" },
  { en: "month", es: "mes", cat: "time" },
  { en: "year", es: "año", cat: "time" },
  { en: "today", es: "hoy", cat: "time" },
  { en: "tomorrow", es: "mañana", cat: "time" },
  { en: "yesterday", es: "ayer", cat: "time" },
  { en: "sun", es: "sol", cat: "time" },
  { en: "moon", es: "luna", cat: "time" },
  { en: "rain", es: "lluvia", cat: "time" },
  { en: "snow", es: "nieve", cat: "time" },
  { en: "wind", es: "viento", cat: "time" },
  { en: "tree", es: "árbol", cat: "time" },
  { en: "flower", es: "flor", cat: "time" },

  // Adjectives
  { en: "big", es: "grande", cat: "adjectives" },
  { en: "small", es: "pequeño", cat: "adjectives" },
  { en: "good", es: "bueno", cat: "adjectives" },
  { en: "bad", es: "malo", cat: "adjectives" },
  { en: "new", es: "nuevo", cat: "adjectives" },
  { en: "old", es: "viejo", cat: "adjectives" },
  { en: "happy", es: "feliz", cat: "adjectives" },
  { en: "sad", es: "triste", cat: "adjectives" },
  { en: "hot", es: "caliente", cat: "adjectives" },
  { en: "cold", es: "frío", cat: "adjectives" },
  { en: "easy", es: "fácil", cat: "adjectives" },
  { en: "difficult", es: "difícil", cat: "adjectives" },
  { en: "fast", es: "rápido", cat: "adjectives" },
  { en: "slow", es: "lento", cat: "adjectives" },
  { en: "expensive", es: "caro", cat: "adjectives" },
  { en: "cheap", es: "barato", cat: "adjectives" },

  // Verbs
  { en: "to eat", es: "comer", cat: "verbs" },
  { en: "to drink", es: "beber", cat: "verbs" },
  { en: "to speak", es: "hablar", cat: "verbs" },
  { en: "to read", es: "leer", cat: "verbs" },
  { en: "to write", es: "escribir", cat: "verbs" },
  { en: "to live", es: "vivir", cat: "verbs" },
  { en: "to work", es: "trabajar", cat: "verbs" },
  { en: "to sleep", es: "dormir", cat: "verbs" },
  { en: "to walk", es: "caminar", cat: "verbs" },
  { en: "to run", es: "correr", cat: "verbs" },
  { en: "to buy", es: "comprar", cat: "verbs" },
  { en: "to sell", es: "vender", cat: "verbs" },
  { en: "to open", es: "abrir", cat: "verbs" },
  { en: "to close", es: "cerrar", cat: "verbs" },
  { en: "to learn", es: "aprender", cat: "verbs" },
  { en: "to understand", es: "entender", cat: "verbs" },
  { en: "to want", es: "querer", cat: "verbs" },
  { en: "to know", es: "saber", cat: "verbs" },

  // Professions
  {
    en: "lawyer",
    es: "abogado",
    cat: "professions",
    gender: "pair",
    m: "abogado",
    f: "abogada",
    enM: "lawyer",
    enF: "lawyer",
  },
  {
    en: "air steward",
    es: "azafato",
    cat: "professions",
    gender: "pair",
    m: "azafato",
    f: "azafata",
    enM: "air steward",
    enF: "air steward",
  },
  {
    en: "firefighter",
    es: "bombero",
    cat: "professions",
    gender: "pair",
    m: "bombero",
    f: "bombera",
    enM: "firefighter",
    enF: "firefighter",
  },
  {
    en: "singer",
    es: "cantante",
    cat: "professions",
    gender: "pair",
    m: "cantante",
    f: "cantante",
    enM: "singer",
    enF: "singer",
    invariable: true,
  },
  {
    en: "designer",
    es: "diseñador",
    cat: "professions",
    gender: "pair",
    m: "diseñador",
    f: "diseñadora",
    enM: "designer",
    enF: "designer",
  },
  {
    en: "electrician",
    es: "electricista",
    cat: "professions",
    gender: "pair",
    m: "electricista",
    f: "electricista",
    enM: "electrician",
    enF: "electrician",
    invariable: true,
  },
  {
    en: "nurse",
    es: "enfermero",
    cat: "professions",
    gender: "pair",
    m: "enfermero",
    f: "enfermera",
    enM: "nurse",
    enF: "nurse",
  },
  {
    en: "plumber",
    es: "fontanero",
    cat: "professions",
    gender: "pair",
    m: "fontanero",
    f: "fontanera",
    enM: "plumber",
    enF: "plumber",
  },
  {
    en: "photographer",
    es: "fotógrafo",
    cat: "professions",
    gender: "pair",
    m: "fotógrafo",
    f: "fotógrafa",
    enM: "photographer",
    enF: "photographer",
  },
  {
    en: "engineer",
    es: "ingeniero",
    cat: "professions",
    gender: "pair",
    m: "ingeniero",
    f: "ingeniera",
    enM: "engineer",
    enF: "engineer",
  },
  {
    en: "mechanic",
    es: "mecánico",
    cat: "professions",
    gender: "pair",
    m: "mecánico",
    f: "mecánica",
    enM: "mechanic",
    enF: "mechanic",
  },
  {
    en: "doctor",
    es: "médico",
    cat: "professions",
    gender: "pair",
    m: "médico",
    f: "médica",
    enM: "doctor",
    enF: "doctor",
  },
  {
    en: "musician",
    es: "músico",
    cat: "professions",
    gender: "pair",
    m: "músico",
    f: "música",
    enM: "musician",
    enF: "musician",
  },
  {
    en: "journalist",
    es: "periodista",
    cat: "professions",
    gender: "pair",
    m: "periodista",
    f: "periodista",
    enM: "journalist",
    enF: "journalist",
    invariable: true,
  },
  {
    en: "painter",
    es: "pintor",
    cat: "professions",
    gender: "pair",
    m: "pintor",
    f: "pintora",
    enM: "painter",
    enF: "painter",
  },
  {
    en: "police officer",
    es: "policía",
    cat: "professions",
    gender: "pair",
    m: "policía",
    f: "policía",
    enM: "police officer",
    enF: "police officer",
    invariable: true,
  },
  {
    en: "teacher",
    es: "profesor",
    cat: "professions",
    gender: "pair",
    m: "profesor",
    f: "profesora",
    enM: "teacher",
    enF: "teacher",
  },
  {
    en: "lifeguard",
    es: "socorrista",
    cat: "professions",
    gender: "pair",
    m: "socorrista",
    f: "socorrista",
    enM: "lifeguard",
    enF: "lifeguard",
    invariable: true,
  },
  {
    en: "vet",
    es: "veterinario",
    cat: "professions",
    gender: "pair",
    m: "veterinario",
    f: "veterinaria",
    enM: "vet",
    enF: "vet",
  },
];
